[package]
name = "LifeInsurance"
version = "1.0.0"
authors = []

[addresses]
myAddr = "0xcf20380a4029b40503bfb4da2107ad56bce33dc67a6e021ddcf6d0cb542f3053"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "devnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "devnet" }
